import './globals.css'
import type { Metadata } from 'next'
import BottomHeader from '@/components/header/BottomHeader'
import Footer from '@/components/Footer'
import HeaderContainer from '@/components/header/HeaderContainer'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="font-bodyFont">
        <HeaderContainer />
        <BottomHeader />
        {children}
        <Footer />
      </body>
    </html>
  )
}
