import './globals.css'
import type { Metadata } from 'next'
import Footer from '@/components/Footer'
import HeaderContainer from '@/components/header/HeaderContainer'
import AuthProviders from '@/components/AuthProviders'
import ToasterContainer from '@/components/ToasterContainer'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="font-bodyFont">
        <AuthProviders>
          <ToasterContainer />
          <HeaderContainer />
          {children}
          <Footer />
        </AuthProviders>
      </body>
    </html>
  )
}
